<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-H8GD1N65" failures="1" tests="1" name="Test" time="17.021" errors="0" timestamp="2023-07-16T17:23:59 IST">
  <testcase classname="Testngpractice.soucelabpractice" name="testing" time="16.917">
    <failure type="java.lang.AssertionError" message="expected [Thank you for your order] but found [Thank you for your order!]">
      <![CDATA[java.lang.AssertionError: expected [Thank you for your order] but found [Thank you for your order!]
at Testngpractice.soucelabpractice.testing(soucelabpractice.java:101)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testing -->
</testsuite> <!-- Test -->
